name: "Setup ROS environment"

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Setting up the worker, and installing system dependencies on all OSes
jobs:
  # Ubuntu requires its own separate workflow as additional configuration is required for Docker      
  test_docker: # On Linux, iterates on all ROS 1 distributions.
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: melodic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: exercise_1 exercise_2
          target-ros1-distro: melodic
          vcs-repo-file-url: "https://github.com/Andrew1021/AuRo/raw/main/AuRo.repos"

